### ISSUE TITLE
onAdd not working

### ISSUE THREAD

**Issue by yachtkeel** [Frogmouth/jQuery.Wishlist#2]
Hi, great plugin
Just a quick question, am trying to invoke onAdd but it does not work

```
itemOptions : {
    onAdd : function(item){
        $("#wishList ul.dropdown-menu li.mizza").remove();
    },
    onRemove : function(item){
        if($("#wishList ul.dropdown-menu").length == 0) $("#wishList ul.dropdown-menu").append('(li) class="mizza"> No Items Found (/li)');
    },
}
```

**Comment by Frogmouth** [comment]
Hi mate,

Right now I'm really busy, but tomorrow i will find some minutes to help
you to solve the problem (or fix the plugin bug), I promise

Simone

Il giorno mar 21 lug 2015 19:56 yachtkeel <notifications@github.com> ha
scritto:

**Comment by Frogmouth** [comment]
Hi mate,

I'm Busy right now. Tomorrow I will help you. I promise.

But, i think you use an old version of the plugin, please update the plugin and follow this documentation:

https://github.com/Frogmouth/jQuery.Wishlist/blob/master/documentation/wishlist.md

**onAdd** callback is replaced by **onChange** in new release.

;)

**Comment by yachtkeel** [comment]
thank you so much

**Comment by Frogmouth** [comment]
Hi yachtkeel,

in this fiddle i try to solve your problem with new withlist plugin:

http://jsfiddle.net/Frogmouth/bb8qrf9q/

Update your plugin, i found a bug inside onChange Callback, and i fix it in new release.

Simone

**Comment by yachtkeel** [comment]
thanks Simone for the great plugin and your help

**Comment by Frogmouth** [comment]
Thanks to you for support, mate!
If you have some other problems with Wishlist, I'm here.

I close this bug.
;)

**Comment by yachtkeel** [comment]
Hello Simone,
Trust all is fine? Was wondering if it would be possible to have jQuery
wishlist work on mobile? at the moment it does not! Have you got any near
future plans to have it work on mobile devices?

Thanks mate

**Comment by Frogmouth** [comment]
Please Open an other issue.... however, right now wishlist is not "optimized"... so, in some browser with some device, may occur some problems. Thanks for the input... I work to optimize the plugin for mobile (probably there are some problem.
