### ISSUE TITLE
Behavior in a list with ajax updates

### ISSUE THREAD

**Issue by sandrosamueli** [Frogmouth/jQuery.Wishlist#5]
Hello Simone,

I am using your plugin to offer a wishlist function on a page that adds more records with an ajax load script to the bottom scroll.
In the main script I call the build of the plugin after loading the document, and so far so good.
However, when the additional record population script is activated, the added records do not have the behavior of adding or removing from the wishlist.
I have tried many ways to revive it but with no luck.
If I try to invoke window.MYwishlist = $ .Wishlist ("wishlist") in the record update script, it activates the behavior on the added records but it is no longer active on the main page ones.
Do you have any suggestions for me? Could this be a plugin problem?
Thank you!

------------IT--------------

Ciao Simone,

sto usando il tuo plugin per offrire una funzione di wishlist in una pagina che aggiunge altri record con uno script di caricamento ajax allo scroll di fondo pagina.
Nello script principale chiamo la costruzione del plugin al termine del caricamento del documento, e fin qui tutto bene. 
Quando però lo script di ulteriore popolamento di record si attiva, i record aggiunti non hanno il comportamento di aggiunta o rimozione dalla wishlist.
Ho provato in molti modi a rilanciarlo ma senza fortuna.
Se provo a richiamare window.MYwishlist = $.Wishlist("wishlist") nello script di aggiornamento dei record, mi attiva il comportamento sui record aggiunti ma non è più attivo su quelli della pagina principale.
Hai qualche suggerimento da darmi? Può essere un problema del plugin?
Grazie!

**Comment by Frogmouth** [comment]
H[sandrosamueli](https://github.com/sandrosamueli),

the problem is related to the way that I use for instance the `events handler` on "wishable" items that works only with the items presents in page when u instance the wishlist.

Try to run this code, after the ajax call:

```
$(".wishItem").wishItem(MYwishlist.settings.itemOption,MYwishlist);
```
(try also to use a selector `.wishItem` that is specific for only the new elements in the page if you can)

Where `MYwishlist` should be the result of the first wishlist instance:

```
window.MYwishlist = $.Wishlist("wishlist");
```

let me know it solves the issue.

**Comment by sandrosamueli** [comment]
Hi Simone, thanks for your reply.

The solution you proposed did not work for me. What happens, when I implement it, is that the group of elements that is loaded at the beginning becomes inactive and instead the new elements, loaded with ajax, assume the desired behavior.

Instead I solved it with the following code which reuses some constructor steps on the new elements:

`
   $(".wishAction[data-more=**_n_**]").each(function () {
        
            if (typeof window.wishList["wishlist"].data.get($(this).data("id")) !== "undefined") $(this).removeClass("addToWish").addClass("removeToWish");

            $(this).on("click", function (event) {
                event.preventDefault();
                var data = picker($(this));

                if ($(this).hasClass("addToWish")) {
                    window.wishList["wishlist"].addToWish(data);
                    if ("addToWish") $(this).removeClass("addToWish").addClass("removeToWish");
                } else {
                    window.wishList["wishlist"].removeToWish(data.id);
                    if ("addToWish") $(this).removeClass("removeToWish").addClass("addToWish");
                }

                window.wishList["wishlist"].updateStorege();
            });

        });`

Thank you for your time!
